/**
 * Resolve missing parentId values by looking up supervisor names.
 * Also auto-generates missing id values and deduplicates entries.
 * 
 * @param data - Raw array of node data
 * @param nameField - The field name used for node names (default: 'name')
 * @param supervisorFields - Array of field names to check for supervisor references
 * @returns Resolved data array with parentId values filled in
 */
export function resolveMissingParentIds(
  data: any[],
  nameField: string,
  supervisorFields: string[]
): any[] {
  // First pass: deduplicate entries
  const seenIds = new Set<string>();
  const seenNamesForDedup = new Set<string>();
  
  // Check if we're using name-based format (items have names but no IDs)
  const usesNameBasedFormat = data.some(item => item[nameField] !== undefined) &&
                               !data.some(item => item.id !== undefined && item.id !== null);
  
  const deduplicatedData = data.filter(item => {
    // Deduplicate by ID if present
    if (item.id !== undefined && item.id !== null) {
      const idStr = String(item.id);
      if (seenIds.has(idStr)) {
        console.warn(`Duplicate id "${idStr}" detected - ignoring duplicate entry`);
        return false;
      }
      seenIds.add(idStr);
    }
    
    // Also deduplicate by name in name-based format
    if (usesNameBasedFormat && item[nameField]) {
      const nameStr = String(item[nameField]).toLowerCase();
      if (seenNamesForDedup.has(nameStr)) {
        console.warn(`Duplicate name "${item[nameField]}" detected - ignoring duplicate entry`);
        return false;
      }
      seenNamesForDedup.add(nameStr);
    }
    
    return true;
  });

  // Second pass: auto-generate missing ids
  let hasNumericIds = false;
  let maxNumericId = 0;
  const existingIds = new Set<string>();

  for (const item of deduplicatedData) {
    if (item.id !== undefined && item.id !== null) {
      existingIds.add(String(item.id));
      const numId = typeof item.id === 'number' ? item.id : parseInt(String(item.id), 10);
      if (!isNaN(numId) && String(numId) === String(item.id)) {
        hasNumericIds = true;
        if (numId > maxNumericId) {
          maxNumericId = numId;
        }
      }
    }
  }

  // Helper to generate a unique ID
  let autoIdCounter = maxNumericId;
  const generateId = (item: any): string | number => {
    // Prefer email as ID if available
    if (item.email) {
      const emailId = String(item.email).toLowerCase();
      if (!existingIds.has(emailId)) {
        existingIds.add(emailId);
        return emailId;
      }
    }
    
    if (hasNumericIds || existingIds.size === 0) {
      autoIdCounter++;
      return autoIdCounter;
    } else {
      let newId: string;
      do {
        newId = `auto-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;
      } while (existingIds.has(newId));
      existingIds.add(newId);
      return newId;
    }
  };

  // Assign ids to items that don't have them
  const dataWithIds = deduplicatedData.map((item) => {
    if (item.id === undefined || item.id === null) {
      return { ...item, id: generateId(item), _autoGeneratedId: true };
    }
    return item;
  });

  // Build a map of name -> id for quick lookup (first occurrence wins)
  const nameToId = new Map<string, any>();
  const seenNames = new Set<string>();
  for (const item of dataWithIds) {
    const name = item[nameField];
    if (name) {
      const normalizedName = String(name).toLowerCase();
      if (!seenNames.has(normalizedName)) {
        nameToId.set(normalizedName, item.id);
        seenNames.add(normalizedName);
      }
    }
  }

  // Process each item and resolve missing parentId
  return dataWithIds.map(item => {
    // Skip if parentId is already set (including explicit null for root nodes)
    if (item.parentId !== undefined) {
      return item;
    }

    // Try to resolve parentId from supervisor field aliases
    for (const field of supervisorFields) {
      const supervisorName = item[field];
      if (supervisorName) {
        const normalizedName = String(supervisorName).toLowerCase();
        const parentId = nameToId.get(normalizedName);
        if (parentId !== undefined) {
          return { ...item, parentId };
        }
      }
    }

    // No parentId and couldn't resolve from supervisor - treat as root node
    return { ...item, parentId: null };
  });
}
